spring:
  profiles:
    active: dev
  application:
    name: seek-friend-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friend
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1234
    virtual-host: /

server:
  port: 8080
  servlet:
    context-path: /api # 以 api 为前缀


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


# 自定义配置
cross-origin:
  allow-origin: http://127.0.0.1

aliyun:
  oss:
    access-key-id: xx
    access-key-secret: xx
    end-point: xx
    bucket-name: xx
jwt:
  token-secret: sffgrrgr453453
